### ISSUE TITLE
control charater found while parsing a string

### ISSUE THREAD

**Issue by yanzixiang** [datalust/seq-input-gelf#110]
![image](https://user-images.githubusercontent.com/33214/194818183-8e960287-ec93-42be-abcf-d2dbce42e3c3.png)

what does this mean ?
and how to disable this ?

**Comment by KodrAus** [comment]
Thanks for reaching out @yanzixiang, this is possibly similar to #111 so I’ll close this one and we can use that issue to dig into it.
