### ISSUE TITLE
invalid unicode code point ?

### ISSUE THREAD

**Issue by yanzixiang** [datalust/seq-input-gelf#111]
![image](https://user-images.githubusercontent.com/33214/194837430-89e328f1-ab99-4ce0-9aeb-532f016f6961.png)

which range is invalid ?

**Comment by KodrAus** [comment]
Hi @yanzixiang 👋

You might get some more details if you enable additional diagnostics in the App Instance Settings for your GELF input. It looks like you might be getting some non UTF8 input being logged?

**Comment by yanzixiang** [comment]
![image](https://user-images.githubusercontent.com/33214/194977514-bdaf32da-6f01-4d39-85fb-6493a00ce5f7.png)

after I enabled additional diagnostics,
the error is changed to this.

**Comment by KodrAus** [comment]
Ah it looks like we’re only reporting the top-level error and not its more detailed cause.

Do you know where those logs are coming from originally? Are they directly from a system or are they being collected via Docker’s log driver or something similar?

**Comment by yanzixiang** [comment]
i use [gelflib](https://github.com/serge-14/gelflib) send the log from systemd-journald to seq-input-gelf

**Comment by KodrAus** [comment]
I've opened #113 to try improve those error messages a bit so it might be clearer what input you are getting and where it's not valid UTF8.

The fact that your first error suggests the invalid content was encountered pretty far into the document suggests it might be getting truncated somewhere.
