### ISSUE TITLE
The App Process is Stopped

### ISSUE THREAD

**Issue by Slythe** [datalust/seq-input-gelf#122]
Hi,

I'm trying to install this app on my installation of Seq, however when I add an instance of the app it says "The app process is stopped". Searching the logs for the AppInstanceId I see the following (and only this) in the results;

>  Nonzero exit code -1073741515 returned from app process

I've opened the correct port on the firewall and enabled diagnostics but its giving me nothing (This is a windows install and not via docker).

Any ideas?

**Comment by liammclennan** [comment]
Hi @Slythe 

Check that the user Seq is running as is able to bind to whatever port you have configured. 

If that doesn't work, grab a diagnostic report (Settings > Diagnostic) and see if you can find any related error in there.

**Comment by nblumhardt** [comment]
Closing this as stale
